### PR TITLE
Update Node version fallback to support Meteor 1.0.2.1

### PR DESCRIPTION
**Pull request by jaimie-van-santen**

### CODE REVIEW

**Comment by ind1go** [comment]
Thanks again.

**Comment by sjmcdowall** [comment]
Hey guys -- I am trying this on BlueMix using the mongolab service, which I called "mongo100". However, the logic doesn't appear to find the VCAP service as there is no tag "nosql" .. also, it appears the DB uses a URI credential, not URL .. 

Here is the VCAP_SERVICES for my app .. 
{"redis-2.6":[{"name":"redis100","label":"redis-2.6","tags":["key-value","nosql","web_and_app","ibm_experimental"],"plan":"100","credentials":{"hostname":"75.126.23.242","host":"75.126.23.242","port":5156,"password":"18318c86-1bba-4579-8461-eb68b752425c","name":"fc96134b-fb5d-427c-ace0-487309fa2b45"}}],"mongolab":[{"name":"mongo100","label":"mongolab","tags":["Data Stores","Development Tools","Infrastructure","Service","data_management","ibm_third_party"],"plan":"sandbox","credentials":{"uri":"mongodb://IbmCloud_t7vtsm40_icer83ci_84k4gkco:lHAa5aZ5utvf6HOA4DASMlgKKRX_rsEM@ds035760.mongolab.com:35760/IbmCloud_t7vtsm40_icer83ci"}}]}

Any ideas? Thanks!

**Comment by ind1go** [comment]
@sjmcdowall - thanks for the heads-up. Bluemix moved from the community-led Mongo service to the new Mongolab service, which is slightly different. I remember that I actually spotted this a month or so ago and forgot to merge in the changes. Could you try using the 'mongolab' branch for that fix, to test it works for you too? Then I'll merge in. This means you'll do:

cf push [APP_NAME] -b https://github.com/ind1go/bluemix-buildpack-meteor.git#mongolab

Let me know how you get on.

**Comment by sjmcdowall** [comment]
I’ll certainly give it a shot! 

Ok — done !  Well, the good news is that the MONGO_URL looks much better now!  The bad news — is that my app actually doesn’t appear to run .. although it runs fine locally.  Am I supposed to do something first before the cf push?  meteor build or something? 

Thanks!!

Here is all the output … 
—
/Users/sjm/work/galaxy/rts/sources $ cf push RTSDash
Using manifest file /Users/sjm/work/galaxy/rts/sources/manifest.yml

Updating app RTSDash in org galaxysemi / space dev as steven.mcdowall@galaxysemi.com...
OK

Using route gxs-rtsdash.mybluemix.net
Uploading RTSDash...
Uploading app files from: /Users/sjm/work/galaxy/rts/sources/RTSDash
Uploading 3.6M, 676 files
Done uploading               
OK
Binding service mongo100 to app RTSDash in org galaxysemi / space dev as steven.mcdowall@galaxysemi.com...
OK

Stopping app RTSDash in org galaxysemi / space dev as steven.mcdowall@galaxysemi.com...
OK

Starting app RTSDash in org galaxysemi / space dev as steven.mcdowall@galaxysemi.com...
-----> Downloaded app package (6.0M)
-----> Downloaded app buildpack cache (4.0K)
Cloning into '/tmp/buildpacks/bluemix-buildpack-meteor'...
-----> Resolving engine versions
       No version of Node.js specified in nodeversion, using '0.10.33'
       Using Node.js version: 0.10.33
-----> Fetching Node.js binaries
        - downloading and extracting node from http://nodejs.org/dist/v0.10.33/node-v0.10.33-linux-x64.tar.gz
       Installing meteor
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  6121    0  6121    0     0  13075      0 --:--:-- --:--:-- --:--:-- 24484
Downloading Meteor distribution
Dropped log message: message too long (>64K without a newline)
Dropped log message: message too long (>64K without a newline)
Dropped log message: message too long (>64K without a newline)
Dropped log message: message too long (>64K without a newline)
Dropped log message: message too long (>64K without a newline)
Dropped log message: message too long (>64K without a newline)
Dropped log message: message too long (>64K without a newline)
Dropped log message: message too long (>64K without a newline)
######################################################################## 100.0%
Meteor 1.0.3.1 has been installed in your home directory (~/.meteor).
Writing a launcher script to /usr/local/bin/meteor for your convenience.
This may prompt for your password.
sudo: no tty present and no askpass program specified
Couldn't write the launcher script. Please either:
  (1) Run the following as root:
  (2) Add "$HOME/.meteor" to your path, or
  (3) Rerun this command to try again.
Then to get started, take a look at 'meteor --help' or see the docs at
docs.meteor.com.
       Meteor installed
       Building meteor bundle
       WARNING: The output directory is under your source tree.
       Installing meteor bundle
       npm WARN package.json meteor-dev-bundle@0.0.0 No description
       npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
       npm WARN package.json meteor-dev-bundle@0.0.0 No README data
       > fibers@1.0.1 install /tmp/staged/app/.meteor/meteor_build/app/bundle/programs/server/node_modules/fibers
       > node ./build.js
       `linux-x64-v8-3.14` exists; testing
       Binary is fine; exiting
       underscore@1.5.2 node_modules/underscore
       semver@4.1.0 node_modules/semver
       fibers@1.0.1 node_modules/fibers
       eachline@2.3.3 node_modules/eachline
       └── type-of@2.0.1
       source-map-support@0.2.8 node_modules/source-map-support
       └── source-map@0.1.32 (amdefine@0.1.0)
       chalk@0.5.1 node_modules/chalk
       ├── ansi-styles@1.1.0
       ├── escape-string-regexp@1.0.3
       ├── supports-color@0.2.0
       ├── strip-ansi@0.3.0 (ansi-regex@0.2.1)
       └── has-ansi@0.1.0 (ansi-regex@0.2.1)
Setting up MONGO_URL in .profile.d
Looking for a service labelled "mongolab" in the following $VCAP_SERVICES...
{"mongolab":[{"name":"mongo100","label":"mongolab","tags":["Data Stores","Development Tools","Infrastructure","Service","data_management","ibm_third_party"],"plan":"sandbox","credentials":{"uri":"mongodb://IbmCloud_t7vtsm40_icer83ci_84k4gkco:lHAa5aZ5utvf6HOA4DASMlgKKRF_rsEM@ds035760.mongolab.com:35760/IbmCloud_t7vtsm40_icer83ci"}}]}
  #!/bin/sh
  export ROOT_URL=${ROOT_URL:-http://gxs-rtsdash.mybluemix.net}
  export MONGO_URL=${MONGO_URL:-mongodb://IbmCloud_t7vtsm40_icer83ci_84k4gkco:lHAa5aZ5utvf6HOA4DASMlgKKRF_rsEM@ds035760.mongolab.com:35760/IbmCloud_t7vtsm40_icer83ci}
  export
-----> Vendoring node into slug
-----> Uploading droplet (14M)

0 of 1 instances running, 1 starting
0 of 1 instances running, 1 starting
0 of 1 instances running, 1 down
0 of 1 instances running, 1 down
0 of 1 instances running, 1 down
0 of 1 instances running, 1 down
0 of 1 instances running, 1 starting
0 of 1 instances running, 1 starting
0 of 1 instances running, 1 down
FAILED
Start app timeout

—
2015-02-23T15:57:49.88-0500 [STG/97]     OUT -----> Uploading droplet (14M)
2015-02-23T15:57:54.12-0500 [DEA/97]     OUT Starting app instance (index 0) with guid 6710b001-87ee-469a-b7fd-7fb8730042b6
2015-02-23T15:58:10.77-0500 [DEA/97]     ERR Instance (index 0) failed to start accepting connections
2015-02-23T15:58:10.77-0500 [API/7]      OUT App instance exited with guid 6710b001-87ee-469a-b7fd-7fb8730042b6 payload: {"cc_partition"=>"default", "droplet"=>"6710b001-87ee-469a-b7fd-7fb8730042b6", "version"=>"56ee2e5a-9fec-4f87-a60c-c77fa64a6852", "instance"=>"dd884e6e0707455ba3d20f448e4a2a30", "index"=>0, "reason"=>"CRASHED", "exit_status"=>127, "exit_description"=>"failed to accept connections within health check timeout", "crash_timestamp"=>1424725090}
2015-02-23T15:58:10.78-0500 [API/2]      OUT App instance exited with guid 6710b001-87ee-469a-b7fd-7fb8730042b6 payload: {"cc_partition"=>"default", "droplet"=>"6710b001-87ee-469a-b7fd-7fb8730042b6", "version"=>"56ee2e5a-9fec-4f87-a60c-c77fa64a6852", "instance"=>"dd884e6e0707455ba3d20f448e4a2a30", "index"=>0, "reason"=>"CRASHED", "exit_status"=>127, "exit_description"=>"failed to accept connections within health check timeout", "crash_timestamp"=>1424725090}
2015-02-23T15:58:14.25-0500 [DEA/97]     OUT Removing crash for app with id 6710b001-87ee-469a-b7fd-7fb8730042b6
2015-02-23T15:58:14.26-0500 [DEA/97]     OUT Stopping app instance (index 0) with guid 6710b001-87ee-469a-b7fd-7fb8730042b6
2015-02-23T15:58:14.26-0500 [DEA/97]     OUT Stopped app instance (index 0) with guid 6710b001-87ee-469a-b7fd-7fb8730042b6
2015-02-23T15:58:48.16-0500 [DEA/118]    OUT Starting app instance (index 0) with guid 6710b001-87ee-469a-b7fd-7fb8730042b6
2015-02-23T15:59:01.52-0500 [API/1]      OUT App instance exited with guid 6710b001-87ee-469a-b7fd-7fb8730042b6 payload: {"cc_partition"=>"default", "droplet"=>"6710b001-87ee-469a-b7fd-7fb8730042b6", "version"=>"56ee2e5a-9fec-4f87-a60c-c77fa64a6852", "instance"=>"c73ccf3cfbd24834984888969092c549", "index"=>0, "reason"=>"CRASHED", "exit_status"=>127, "exit_description"=>"failed to accept connections within health check timeout", "crash_timestamp"=>1424725141}
2015-02-23T15:59:01.54-0500 [DEA/118]    ERR Instance (index 0) failed to start accepting connections
2015-02-23T15:59:01.55-0500 [API/2]      OUT App instance exited with guid 6710b001-87ee-469a-b7fd-7fb8730042b6 payload: {"cc_partition"=>"default", "droplet"=>"6710b001-87ee-469a-b7fd-7fb8730042b6", "version"=>"56ee2e5a-9fec-4f87-a60c-c77fa64a6852", "instance"=>"c73ccf3cfbd24834984888969092c549", "index"=>0, "reason"=>"CRASHED", "exit_status"=>127, "exit_description"=>"failed to accept connections within health check timeout", "crash_timestamp"=>1424725141}

**Comment by ind1go** [comment]
Hmm, shouldn't need much more than that, so I suggest it's an app problem. To better debug, you may want to run `cf logs [app-name]` in a different terminal while the upload is running.

I'd also suggest, if you haven't already, you create a .cfignore file in the root of the project with the following content, to avoid uploading most of Meteor itself:
    .meteor/local
That should make the upload a bit quicker for you. I'll stick that in the README.

**Comment by sjmcdowall** [comment]
The hint for the .cfignore is great!  

App still not running (and it does run locally) — I’m for sure a newbie when it comes to CF / Bluemix and buildpackages — but what is the command that is actually used to run the application? I looked at the buildpack code but I can’t see where it actually run’s it, so obviously it doesn’t :) 

So not sure how CF knows the actually command to run?  That maybe my issues, I do it on my Mac with “meteor —port XXXX” and I get : 

/Users/sjm/work/galaxy/rts/sources/RTSDash $ cat run.sh 
#!/usr/bin/env bash
MONGO_URL=mongodb://localhost:27017/RTS meteor --port 4000
/Users/sjm/work/galaxy/rts/sources/RTSDash $ ./run.sh 
[[[[[ ~/work/galaxy/rts/sources/RTSDash ]]]]] 

=> Started proxy.                             
I20150223-17:00:50.528(-5)? Meteor App starting..
I20150223-17:00:50.530(-5)? Server - finding testcells :  [ { _id: 'VTESTER203',
I20150223-17:00:50.530(-5)?     vendor: 'Galaxy',
I20150223-17:00:50.530(-5)?     version: 'TCS_VERSION',
I20150223-17:00:50.530(-5)?     status: 'TEST DATA RECEIVED',
I20150223-17:00:50.530(-5)?     lastUpdatedTS: Thu Feb 12 2015 17:02:40 GMT-0500 (EST),
I20150223-17:00:50.530(-5)?     initializedTS: 'Thu Feb 12 2015 16:56:30 GMT-0500 (EST)',
I20150223-17:00:50.530(-5)?     lostMessages: 0,
I20150223-17:00:50.530(-5)?     statusFreq: '0',
I20150223-17:00:50.530(-5)?     lot: 
I20150223-17:00:50.531(-5)?      { currentLot: 'B2001',
I20150223-17:00:50.531(-5)?        lotType: 'FINAL',
I20150223-17:00:50.531(-5)?        failed: 0,
I20150223-17:00:50.531(-5)?        passed: 8,
I20150223-17:00:50.531(-5)?        total: 8,
I20150223-17:00:50.531(-5)?        yield: 1,
I20150223-17:00:50.531(-5)?        hbins: {},
I20150223-17:00:50.531(-5)?        sbins: {} },
I20150223-17:00:50.531(-5)?     user: {},
I20150223-17:00:50.531(-5)?     testerOS: 
I20150223-17:00:50.532(-5)?      { state: 'START_OR_END',
I20150223-17:00:50.532(-5)?        eventType: 'TESTER_OS_EVENT_TYPE',
I20150223-17:00:50.532(-5)?        version: 'VERSION',
I20150223-17:00:50.532(-5)?        mode: 'ONLINE_MODE',
I20150223-17:00:50.532(-5)?        userMode: 'USER_MODE',
I20150223-17:00:50.532(-5)?        userID: 'USER_ID',
I20150223-17:00:50.532(-5)?        display: 'DISPLAY',
I20150223-17:00:50.540(-5)?        sectorList: 'SECTOR_LIST' },
I20150223-17:00:50.540(-5)?     config: {},
I20150223-17:00:50.540(-5)?     testProgram: 
I20150223-17:00:50.540(-5)?      { name: 'Beta_TestPgm_Rev004',
I20150223-17:00:50.540(-5)?        sub_program: 'TEST_SUBPROGRAM',
I20150223-17:00:50.540(-5)?        state: 'END',
I20150223-17:00:50.540(-5)?        loadEvent: 'LOAD_EVENT',
I20150223-17:00:50.541(-5)?        userID: 'USER_ID',
I20150223-17:00:50.541(-5)?        status: 'READY' },
I20150223-17:00:50.541(-5)?     id: 'VTESTER203',
I20150223-17:00:50.541(-5)?     batch: 
I20150223-17:00:50.541(-5)?      { batchID: 'Beta',
I20150223-17:00:50.541(-5)?        failed: 15,
I20150223-17:00:50.541(-5)?        passed: 98,
I20150223-17:00:50.541(-5)?        total: 113,
I20150223-17:00:50.542(-5)?        yield: 0.8672566371681416 } } ]
=> Started your app.

=> App running at: http://localhost:4000/ <http://localhost:4000/>


And it’s alive just fine — but I am getting NOTHING out of cf logs .. besides the fact it didn’t seem to listen .. 

2015-02-23T16:58:33.44-0500 [DEA/124]    OUT Stopped app instance (index 0) with guid 6710b001-87ee-469a-b7fd-7fb8730042b6
2015-02-23T16:58:52.77-0500 [DEA/94]     OUT Starting app instance (index 0) with guid 6710b001-87ee-469a-b7fd-7fb8730042b6
2015-02-23T16:58:52.77-0500 [API/2]      OUT Updated app with guid 6710b001-87ee-469a-b7fd-7fb8730042b6 ({"state"=>"STARTED"})
2015-02-23T16:59:04.82-0500 [DEA/94]     ERR Instance (index 0) failed to start accepting connections
2015-02-23T16:59:04.86-0500 [API/0]      OUT App instance exited with guid 6710b001-87ee-469a-b7fd-7fb8730042b6 payload: {"cc_partition"=>"default", "droplet"=>"6710b001-87ee-469a-b7fd-7fb8730042b6", "version"=>"529558ea-cf11-4ffa-abee-a4d357f5c7ca", "instance"=>"fe8346ec52aa4ad09340a05f14769b73", "index"=>0, "reason"=>"CRASHED", "exit_status"=>127, "exit_description"=>"failed to accept connections within health check timeout", "crash_timestamp"=>1424728744}
2015-02-23T16:59:08.26-0500 [API/6]      OUT App instance exited with guid 6710b001-87ee-469a-b7fd-7fb8730042b6 payload: {"cc_partition"=>"default", "droplet"=>"6710b001-87ee-469a-b7fd-7fb8730042b6", "version"=>"529558ea-cf11-4ffa-abee-a4d357f5c7ca", "instance"=>"fe8346ec52aa4ad09340a05f14769b73", "index"=>0, "reason"=>"CRASHED", "exit_status"=>127, "exit_description"=>"failed to accept connections within health check timeout", "crash_timestamp"=>1424728744}
2015-02-23T16:59:15.70-0500 [DEA/88]     ERR Instance (index 0) failed to start accepting connections
2015-02-23T16:59:15.71-0500 [API/2]      OUT App instance exited with guid 6710b001-87ee-469a-b7fd-7fb8730042b6 payload: {"cc_partition"=>"default", "droplet"=>"6710b001-87ee-469a-b7fd-7fb8730042b6", "version"=>"b97ae3e7-8ed9-4c52-b0af-a9e4e0c1a81e", "instance"=>"842a105f3d49454cb2b3ac40657c92f0", "index"=>0, "reason"=>"CRASHED", "exit_status"=>127, "exit_description"=>"failed to accept connections within health check timeout", "crash_timestamp"=>1424728755}
2015-02-23T17:00:10.88-0500 [API/5]      OUT App instance exited with guid 6710b001-87ee-469a-b7fd-7fb8730042b6 payload: {"cc_partition"=>"default", "droplet"=>"6710b001-87ee-469a-b7fd-7fb8730042b6", "version"=>"b97ae3e7-8ed9-4c52-b0af-a9e4e0c1a81e", "instance"=>"e81bd71d08bf45c69e07203611a218ff", "index"=>0, "reason"=>"CRASHED", "exit_status"=>127, "exit_description"=>"failed to accept connections within health check timeout", "crash_timestamp"=>1424728810}
2015-02-23T17:00:10.89-0500 [DEA/124]    ERR Instance (index 0) failed to start accepting connections
2015-02-23T17:00:13.38-0500 [API/1]      OUT Updated app with guid 6710b001-87ee-469a-b7fd-7fb8730042b6 ({"state"=>"STOPPED"})


Anyway, any help you’re willing to give this newbie is most appreciated! 

Cheers!

/Steve

**Pull request merged**
